[CaseData]
git-tree-sha1 = "7c3e2964b4c82b99134db7d2242e12a975321329"
lazy = true

    [[CaseData.download]]
    url = "https://github.com/NREL-Sienna/PowerSystemsTestData/archive/refs/tags/4.0-RC1.tar.gz"
    sha256 = "4b66f17e81065fa8dfd49b0d36bad9ea14f3fe8e712208d6f9fed58db8ca1149"

[rts]
git-tree-sha1 = "c257b2c37b981f261fdc328b0fb9b96436a96537"
lazy = true

    [[rts.download]]
    url = "https://github.com/GridMod/RTS-GMLC/archive/refs/tags/v0.2.3.tar.gz"
    sha256 = "993429b8dc5f096e62479ca3b8551d52a53941322b452c825d12881cda915eae"
