[CaseData]
git-tree-sha1 = "cd54e152c8961febe85cc5b438d97c44abf172a3"
lazy = true

    [[CaseData.download]]
    url = "https://github.com/NREL-Sienna/PowerSystemsTestData/archive/refs/tags/4.0-RC2.tar.gz"
    sha256 = "c9ac899c1e877bea0c115e781c1c1e7d25d9acff6320e48ab2b5b2e5c69d4851"

[rts]
git-tree-sha1 = "c257b2c37b981f261fdc328b0fb9b96436a96537"
lazy = true

    [[rts.download]]
    url = "https://github.com/GridMod/RTS-GMLC/archive/refs/tags/v0.2.3.tar.gz"
    sha256 = "993429b8dc5f096e62479ca3b8551d52a53941322b452c825d12881cda915eae"
