[CaseData]
git-tree-sha1 = "8dd82ef8ac86f095c68b933b3aefb0f96aa7bb1b"
lazy = true

    [[CaseData.download]]
    url = "https://github.com/NREL-Sienna/PowerSystemsTestData/archive/refs/tags/4.0.0.tar.gz"
    sha256 = "2a98597ce1080b0087fd94e625a8f11111969ecd327ec8054aa11ce3ae1ef401"

[rts]
git-tree-sha1 = "c257b2c37b981f261fdc328b0fb9b96436a96537"
lazy = true

    [[rts.download]]
    url = "https://github.com/GridMod/RTS-GMLC/archive/refs/tags/v0.2.3.tar.gz"
    sha256 = "993429b8dc5f096e62479ca3b8551d52a53941322b452c825d12881cda915eae"
