name = "PowerSystemCaseBuilder"
uuid = "f00506e0-b84f-492a-93c2-c0a9afc4364e"
authors = ["Sourabh Dalvi", "Jose Daniel Lara"]
version = "1.0.3"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
CSV = "~0.10"
DataFrames = "1"
DataStructures = "~0.18"
HDF5 = "0.16"
InfrastructureSystems = "^1.21"
PowerSystems = "2"
PrettyTables = "2"
TimeSeries = "~0.22, 0.23"
julia = "^1.6"
